---
deployment:
  tasks:
    - export DEPLOYPATH=/home/ericbhtn/apps/portfolio
    - /bin/mkdir -p $DEPLOYPATH
    - git submodule sync --recursive
    - git submodule update --init --recursive
    - /bin/cp -R static $DEPLOYPATH
    - /bin/cp -R templates $DEPLOYPATH
    - /bin/cp app.py $DEPLOYPATH
